#!/usr/bin/env python3
"""Generate the learning and review menu entries from selected docs/ files.

The generated module is used by the SPA routes, the learning sidebar, and the
learning sidebar. Run this after changing docs; Dockerfile runs it too so a
push always deploys the exact document set bundled in the image.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOCS_DIR = ROOT / "docs"
OUT_MODULE = ROOT / "app" / "frontend" / "js" / "data" / "learnDocs.js"
LEARN_DOCS = (
    ("03", "주식 1"),
    ("05", "주식 2"),
    ("04", "주식 3"),
    ("06", "주식 4"),
    ("07", "주식 5"),
)
REVIEW_DOCS = (
    ("10-1", "법인과 회사 구조 1: 시작하기"),
    ("10-2", "법인과 회사 구조 2: 운영·자금"),
    ("10-3", "법인과 회사 구조 3: 세무·회계"),
    ("11", "거시경제와 주식시장"),
)


def title_for(path: Path) -> str:
    for line in path.read_text(encoding="utf-8").splitlines():
        match = re.match(r"^#\s+(.+?)\s*$", line)
        if match:
            return re.sub(r"^(?:Day|DAY)\s+\d+\s*[—-]\s*", "", match.group(1)).strip()
    return path.stem


def main() -> None:
    def load_docs(entries: tuple[tuple[str, str], ...]) -> list[dict[str, str]]:
        docs = []
        for doc_id, label in entries:
            path = DOCS_DIR / f"{doc_id}.md"
            title = title_for(path)
            docs.append({"id": doc_id, "file": path.name, "title": title, "label": label})
        return docs

    learn_docs = load_docs(LEARN_DOCS)
    review_docs = load_docs(REVIEW_DOCS)
    docs = [*learn_docs, *review_docs]

    # index.html의 사이드바 메뉴는 GNB 드롭다운으로 대체되며 더 이상 문서별 개별
    # 항목을 나열하지 않으므로(핵심 이론 학습은 대표 진입점 2개 + learn.js 자체 목차로
    # 나머지에 접근), 이 스크립트는 SPA/학습 뷰가 실제로 쓰는 learnDocs.js만 생성한다.
    OUT_MODULE.write_text(
        "// Generated by scripts/sync_learning_menu.py from docs/*.md. Do not edit manually.\n"
        f"export const LEARN_DOCS = {json.dumps(docs, ensure_ascii=False, indent=2)};\n",
        encoding="utf-8",
    )
    print(f"학습 메뉴 동기화 완료: 일반 {len(learn_docs)}개, 지난주 정리 {len(review_docs)}개")


if __name__ == "__main__":
    main()
